# Generated by Django 5.1.1 on 2024-10-18 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tema3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tema3.cliente')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tema3.libro')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='libros',
            field=models.ManyToManyField(related_name='libros', through='Tema3.Prestamo', to='Tema3.libro'),
        ),
        migrations.DeleteModel(
            name='Prestamos',
        ),
    ]
